### ISSUE TITLE
Weapons managment system

### ISSUE THREAD

**Issue by YogurtTheHorse** [Skipverja/ShipGame#3]
Add a few weapons to game and setup basic weapon system. It must:
- Manage weapon select 
- Manage enabled weapons
- Setup weapons abstractions

**Comment by Orfac** [comment]
### Cannon
Cannon shoots buckshot in both directions from the ship. 

### Speed guns
It shoots faster than other guns, but it needs a reload after 6 shots, like a revolver

### Plunging guns
It is implementation of plunging fire. Bullet flies over the islands and falls from the sky
